FROM python:3.9-slim

WORKDIR /app

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

RUN uv pip install --system --no-cache-dir mlflow==2.8.1

RUN mkdir -p /mlflow && chmod 777 /mlflow

EXPOSE 5000

ENV PYTHONUNBUFFERED=1

CMD ["mlflow", "server", "--host", "0.0.0.0"]
