version: '3'

services:
  mlflow:
    build:
      context: .
      dockerfile: Dockerfile.mlflow
    container_name: mlflow-server
    volumes:
      - mlflow-data:/mlflow
    ports:
      - "5050:5000"
    command: >
      mlflow server 
      --host 0.0.0.0
    networks:
      - mlflow-network
    restart: always

  model-training:
    build:
      context: .
      dockerfile: Dockerfile.model
    container_name: ml-model-training
    depends_on:
      - mlflow
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow-server:5000
    networks:
      - mlflow-network
    restart: "no"  # Run once and exit

networks:
  mlflow-network:
    driver: bridge

volumes:
  mlflow-data:
